name: CI
on:
  workflow_dispatch:
      
jobs:
  run-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          java -jar w01al.jar
